In [1]:
import pandas as pd

In [2]:
df_ventas = pd.read_csv('ventas.csv')
df_ventas.head()

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,id_cliente,total
0,1,2024-04-12T00:00:00.000000,Monitor,Electrónica,4,187.05,17,748.20
1,2,2024-06-28T00:00:00.000000,Mochila,Informática,7,317.99,1,2225.93
2,3,2024-04-02T00:00:00.000000,Monitor,Electrónica,3,318.60,16,955.80
3,4,2024-01-15T00:00:00.000000,Mochila,Electrónica,6,270.21,12,1621.26
4,5,2024-04-16T00:00:00.000000,Monitor,Informática,2,49.69,19,99.38

In [3]:
df_clientes = pd.read_json('clientes.json')
print(df_clientes.shape[0])

20

In [4]:
df_inventario = pd.read_excel('inventario.xlsx')
df_inventario.head()

,id_producto,producto,categoria,stock_disponible,precio_reposicion,proveedor
0,1,Auriculares,Accesorios,116,65.98,ProveedorB
1,2,Mouse,Accesorios,128,50.71,ProveedorB
2,3,Teclado,Electrónica,15,138.73,ProveedorA
3,4,Monitor,Informática,68,39.44,ProveedorC
4,5,Webcam,Accesorios,21,40.38,ProveedorA

In [5]:
promedio_stock = df_inventario['stock_disponible'].mean()
print(promedio_stock)

82.25